### ISSUE TITLE
play.py (23) - HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by sneschalmer5** [aussieaddons/plugin.video.netball-live#333]
Getting this with version 1.2.0.
play.py (23) - HTTPError: 500 Server Error: Internal Server Error for url: https://hub.telstra.com.au/login/saml_login

AFL Live still connects to Telstra and streams fine.

**Comment by glennguy** [comment]
I'll have a look at it, I think I know what the issue might be. Will get to
it in the next couple of days hopefully.

**Comment by glennguy** [comment]
@sneschalmer5 v1.2.1 is now up and I've fixed this issue. Tested on the replays and all is working well. Let me know how you go!

Cheers

Glenn

**Comment by sneschalmer5** [comment]
Great work. Replays working here as well. Will test the live games this afternoon. Will have some veryt happy girls in this household!
