### ISSUE TITLE
play.py (23) Too many 500 error responses

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#334]
Hi,

Logging in to view the catchup games and getting the above error. Have confirmed the credentials are correct.

Log file attached.

Log file [https://paste.kodi.tv/zubusuzuso](url)

Would appreciate any help, my wife is excited that we have this :)

Cheers.

**Comment by glennguy** [comment]
Hi @JZXPacky 

Thanks for the debug log! I can't see the error in the log though - looks like you had just restarted your mac. Could you reproduce the error and then provide a new log?

**Comment by JZXPacky** [comment]
I reuploaded to the first post. See if that helps.

**Comment by glennguy** [comment]
Thanks for that.

No idea what could be causing it but lets go through a few things...

Are you behind any sort of VPN/smart DNS/getflix etc?
What other services are attached to your Telstra ID? I know it doesn't like it if home broadband or landlines are on your ID. 
Can you confirm your Telstra ID works if you activate your live pass on mobile/tablet on wifi only? (not sure about iOS, try uninstall/reinstall) but on Android clear the data/cache for the app and see if you can get it going. Make sure not to let it activate on the mobile network.
If you can't get it going on wifi on your mobile device, signing up for a fresh Telstra ID (use a throwaway or your wife's email address) and just linking to your eligible mobile service should do the trick.

**Comment by JZXPacky** [comment]
Sorry meant to reply the other day.

I was testing this on my mac before installing it on my RPi's, but I ended up just installing it on the Pi's and it was fine. I'm not going to worry about the issue on the Mac as it was just a test environment.

Thank you anyway :)
