### ISSUE TITLE
Latest content not in app

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#335]
Hi guys,

I can't find any of the latest content for the Constellation Cup on the Netball Live addon, the last things on there were the finals for the Suncorp Super Netball.

Can you please check it out?

Logfile: [https://paste.kodi.tv/tikehafepe](url)

**Comment by glennguy** [comment]
Hi @JZXPacky 

Thanks for opening this issue!

I've just released version 1.3.1, should be in both repos now. All replays available are now showing and the upcoming matches are working again in the live section.

Let me know if there's any further issues

Cheers

Glenn

**Comment by JZXPacky** [comment]
Love the speedy response, all working again!

One very happy pregnant wife! Thank you very much.

**Comment by glennguy** [comment]
Great to hear, happy to help
