### ISSUE TITLE
Error - version outdated but no update available

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#337]
Hi there,

My wife just tried to use the addon today, but it is saying to update to version 1.4.0 (have 1.3.1 installed), but there is no update available in any of the repos?

Has the repo changed at all?
![Snipaste_2020-03-03_09-58-15](https://user-images.githubusercontent.com/26926362/75729127-8ab52a80-5d35-11ea-9c41-289ffaa3b376.jpg)

**Comment by glennguy** [comment]
Hey @JZXPacky 

Maybe you have a very old version of the repo that points to our old github repo.... if the link is no longer redirecting to our new repo (which I believe was supposed to happen after some time) then it can't update any addons. 

To be sure you have the current repo, uninstall the repo on your system and install the up to date version from [here](http://aussieaddons.com/installation/)

**Comment by JZXPacky** [comment]
I’ve followed the instructions to update the addon repo, but it still only shows version 1.3.1

**Comment by glennguy** [comment]
Sorry, just worked it out.

The latest update didn't 'build' properly. I'll get it sorted later tonight and 1.4.1 should be available for real :)

**Comment by JZXPacky** [comment]
Perfect, thank you.
