### ISSUE TITLE
Too many 500 error responses

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#338]
That time of year again. Looks like something has changed. Any chance you can have a look at this again?
![15962388241648995266572455879497](https://user-images.githubusercontent.com/26926362/89088344-19100400-d3db-11ea-9924-81b24d6b49fd.jpg)

**Comment by glennguy** [comment]
@JZXPacky on it, will get it sorted soon hopefully!

**Comment by JZXPacky** [comment]
Awesome, thanks mate.

**Comment by glennguy** [comment]
All done, version 1.4.2 is now in the repo.

Just force our repo to check for updates (Kodi only checks every 6 hours or on restart)

Go into addons and into 'Install from repository'
Highlight our repo and bring up the context menu ('c' on keyboard, long press on remote, right click) and from the menu choose 'check for updates'
If it doesn't auto update then you can go into our repo and install from there.

Let me know how you get on

Cheers

Glenn

**Comment by JZXPacky** [comment]
Just updated but the match won't play unfortunately. Screenshot of error below.
![15962508826418934409633056260844](https://user-images.githubusercontent.com/26926362/89092668-20dda180-d3f7-11ea-9648-a1974e82d7d7.jpg)

**Comment by glennguy** [comment]
Sorry! Thanks for letting me know, I'll get to it in an hour or so. Unfortunately can't test unless there's a match on :(

**Comment by glennguy** [comment]
I've gotta go out for a short while but I'll quickly capture the data so I know what needs doing 🙂

**Comment by JZXPacky** [comment]
All good mate, I understand. I do IT for a living so know it all to well. I really appreciate it.

**Comment by glennguy** [comment]
I'll have to have a look later tonight....

**Comment by JZXPacky** [comment]
Hi Glenn, just wondering if you had a chance to look at it last night?

**Comment by glennguy** [comment]
yep, I think I had it sorted just testing now

**Comment by glennguy** [comment]
@JZXPacky done!
Just force update again as described above.

**Comment by JZXPacky** [comment]
Unfortunately no love. Updated, clicked on live match, it logged in etc but wouldn't start video feed. It's connecting as the score is showing in the live match screen.

**Comment by glennguy** [comment]
Hmm....
Can you check that inputstream.adaptive is installed and enabled - should be in my addons -> VideoPlayer InputStream
Other than that, could you turn on debug logging, try to play video again and then submit a error report from netball addon settings, then I'll have a look and see what the issue is on your end

**Comment by JZXPacky** [comment]
Just had a poke around. Unfortunately live matches are over for this week. The replays are working though. I'll test live match next time and report back.

**Comment by glennguy** [comment]
There's one more match this weekend, stream has now started if you want to check?

**Comment by JZXPacky** [comment]
Ah forgot about that one. Just tried and failed. Uploaded logs. 

![20200802_173259](https://user-images.githubusercontent.com/26926362/89118129-9c6a4c00-d4e6-11ea-817c-1fed059f56a8.jpg)

**Comment by glennguy** [comment]
Hmm the log didn't attach, I'll have to investigate
But I've worked out the issue - inputstream adaptive on Kodi 17 doesn't support the file format of the live streams.

I'll push out an update to try and handle that but you have two solutions right now that will get you playback:
* Upgrade (I'm assuming) LibreELEC to 9.2.x or
* Disable inputstream.adaptive in add-ons

**Comment by JZXPacky** [comment]
Ok so I've updated to the latest version of LibreElec, hopefully that will sort the issues out. Seems I disabled auto updates when I installed it so was running 8.3 still.

When the next live match is on I'll test and let you know. Thanks again.

**Comment by JZXPacky** [comment]
Just got a chance to test and all working now. Thanks again for your help mate.

**Comment by glennguy** [comment]
Awesome, happy to help!
