### ISSUE TITLE
No new replays

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#339]
Hi Glenn,

Are you able to have a look at the addon, as there are none of the latest full match replays showing up. My wife tells me that it is working fine in the app on her phone, so they must have changed something.

Live Matches are working though, and so is the News and Other Videos section.

Running version 1.4.5_leia

Cheers,
Luke.

**Comment by glennguy** [comment]
@JZXPacky they're there, just buried half way down the list.

The current behavior is both super netball and international replays are in the one list - all super netball first and then all international. It's probably a pita to scroll through 240 items though.... Also this is the same for the news+other videos list, but only a page or so of content there so not a big deal.

Two possible solutions:

* Keep the same layout and sort everything by date
* Make a sub menu under each both top level categories to choose super/int

Personally I think first option is best (and also easiest :smile: )

What do you think?

**Comment by JZXPacky** [comment]
Just checked and can see them. Sorry about that.

But if you wanted to do a chronological sort that would be good.

Appreciate the quick reply as always.

**Comment by glennguy** [comment]
All good, I didn't check first either, assumed something else may be to blame haha.

v1.4.6 is in the repo now, sorted by the timestamp given in their API. There's a couple of replays at the bottom that are slightly out of order but it's on their end.

Force update the repo tomorrow if it's not already updated on your machine.
Cheers!

**Comment by JZXPacky** [comment]
Love your work as always! Already updated.

Cheers mate.
