### ISSUE TITLE
No live stream available

### ISSUE THREAD

**Issue by Mark4776** [aussieaddons/plugin.video.netball-live#340]
Have installed latest version and can see the live game I want to watch listed but can't actually get it to play. Have put my username and password in and can watch match replays but not live matches. Is there anything else I need to do?

**Comment by Mark4776** [comment]
Got it fixed by disabling the inputstream.adaptive in add-ons as mentioned in a previous issue. 
I am running Libreelec 9.02 on an Odroid C2 with the latest version of the add-on running.

**Comment by glennguy** [comment]
Great work getting it sorted.

You should consider though upgrading LibreELEC as you should then get a newer version of inputstream adaptive which will work correctly

**Comment by Mark4776** [comment]
Unfortunately there is no LibreElec upgrade higher for the Odroid C2. Might be time for a new board :)

**Comment by glennguy** [comment]
You could probably find a newer Kodi 18 Libreelec inputstream.adaptive zip, it should be compatible.
