### ISSUE TITLE
Cant watch live games

### ISSUE THREAD

**Issue by JZXPacky** [aussieaddons/plugin.video.netball-live#341]
Hi Glenn,

Time for the yearly ticket lol. My wife is trying to watch live games but they are just showing as upcoming and not playable.

Running version 1.5.0_leia.

Any help would be appreciated. Do you want a log?

Cheers,
Luke.

**Comment by glennguy** [comment]
Hey Luke,

Thanks for letting me know, should be able to get onto it tomorrow afternoon. No log needed.

**Comment by glennguy** [comment]
Unfortunate news for you:
![image](https://user-images.githubusercontent.com/11909320/160274185-ee1d29b7-8c7c-48bd-be64-3bece8c60e69.png)

Looks like Kayo/Foxtel is the only way forward for you here :(

**Comment by glennguy** [comment]
Source for the above: https://www.telstra.com.au/support/category/entertainment/sports/what-is-the-netball-live-app
Looks like 'Kayo freebies' at least does all the Diamonds matches (not sure if live or just replay)

**Comment by JZXPacky** [comment]
Yeah we found that out today too. Bit of a shame as the Netball Live plugin you made was great, and you always provided great support.

Thanks again Glenn.
